#!/usr/bin/env bash
# Displays information about subdomains

info() {
	local domain="$1"
	local subdomain="$2"
	local line
	line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
	echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

if [ "$#" -eq 1 ]; then
	info "$1" "www"
	info "$1" "lb-01"
	info "$1" "web-01"
	info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
	info "$1" "$2"
fi
