#!/usr/bin/env bash
# Installs Nginx on an Ubuntu server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
