#!/usr/bin/env bash
# Configures a new Nginx server with a custom HTTP header response

# Updating Packages and installing Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Updating the index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Performing a 301
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/yousafesaeed permanent;/" /etc/nginx/sites-enabled/default

# Creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-enabled/default

# Creating an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations and restarting Nginx
sudo nginx -t
sudo service nginx restart
