#!/usr/bin/env bash
# Configures a new Nginx server with a HAproxy load-balancer

# Updating Packages and installing HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# Editing config file
server_config="
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 296530-web-01 34.234.201.130:80 check
        server 296530-web-02 54.236.51.83:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enabling haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing configurations and restarting Nginx
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
