#!/usr/bin/env bash
# Configures a new Nginx server with a HAproxy load-balancer
sudo apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen thelaura' /etc/haproxy/haproxy.cfg
sed -i '/listen thelaura/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 19994-web-01 3.239.120.182 check' /etc/haproxy/haproxy.cfg
sed -i '/server 19994-web-01 3.239.120.182 check/a         server 19994-web-02 3.237.26.100 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sudo service haproxy start
