#!/usr/bin/env bash
# Fixed a problem regarding port 80 by deleting the Nginx config file and replacing it with a symbolic link
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
