#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using while loop and IFS

while IFS= read -r line; do
    username=$(echo "$line" | cut -f 1 -d ':')
    password=$(echo "$line" | cut -f 2 -d ':')
    user_id=$(echo "$line" | cut -f 3 -d ':')
    user_info=$(echo "$line" | cut -f 5 -d ':')
    group_id=$(echo "$line" | cut -f 4 -d ':')
    command=$(echo "$line" | cut -f 7 -d ':')
    home=$(echo "$line" | cut -f 6 -d ':')

    echo -n "The user $username is part of the $group_id gang, "
    echo -n "lives in $home and rides $command."
    echo -n " $user_id's place is protected by the passcode $password, "
    echo "more info about the user here: $user_info"
done <"/etc/passwd"
